name: Build and Run Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -f docker/Dockerfile -t gerenciamento_acesso .

    - name: Run Docker Container
      run: |
        docker run -d -p 5000:5000 gerenciamento_acesso --privileged

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -f docker/Dockerfile -t firmware-project .

      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name firmware-container firmware-project

      - name: Run server test
        run: |
          python3 /server/test/test_server.py
